[general]
import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]

[env]
term = "xterm-256color"
# term = "screen-256color"

[window]
padding = { x = 1, y = 1 }
decorations_theme_variant = "Dark"
opacity = 0.92
dynamic_padding = true
option_as_alt = "Both"
blur = true

[font]
size = 10.0
offset = { x = 0, y = 1 }
glyph_offset = { x = 0, y = 0 }
builtin_box_drawing = true

[font.normal]
family = "JetBrainsMonoNerdFont"

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 750
thickness = 0.15

[keyboard]
bindings = [
  # Make Alt+backspace delete whole words
  { key = "Back", mods = "Alt", chars = "\u001b\u007f" },
  # Make Alt+left/right move between words
  { key = "Left", mods = "Alt", chars = "\u001b[1;5D" },
  { key = "Right", mods = "Alt", chars = "\u001b[1;5C" },
]

# Scrolling behavior
[scrolling]
history = 10000
multiplier = 3

[mouse]
hide_when_typing = true

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true
