return {}
-- return {
--   "seblyng/roslyn.nvim",
--   ft = "cs",
--   opts = {},
--   config = function(_, opts)
--     require("roslyn").setup(opts)
--
--     -- Configure the LSP server command
--     vim.lsp.config("roslyn", {
--       cmd = {
--         vim.fn.expand("~/.local/share/roslyn-ls/content/LanguageServer/linux-x64/Microsoft.CodeAnalysis.LanguageServer"),
--         "--logLevel=Information",
--         "--extensionLogDirectory=" .. vim.fn.stdpath("log") .. "/roslyn",
--         "--stdio",
--       },
--       cmd_env = {
--         DOTNET_ROOT = vim.fn.expand("~/.local/share/mise/installs/dotnet/10.0.101"),
--       },
--       settings = {
--         ["csharp|inlay_hints"] = {
--           csharp_enable_inlay_hints_for_implicit_object_creation = true,
--           csharp_enable_inlay_hints_for_implicit_variable_types = true,
--           csharp_enable_inlay_hints_for_lambda_parameter_types = true,
--           csharp_enable_inlay_hints_for_types = true,
--           dotnet_enable_inlay_hints_for_indexer_parameters = true,
--           dotnet_enable_inlay_hints_for_literal_parameters = true,
--           dotnet_enable_inlay_hints_for_object_creation_parameters = true,
--           dotnet_enable_inlay_hints_for_other_parameters = true,
--           dotnet_enable_inlay_hints_for_parameters = true,
--           dotnet_suppress_inlay_hints_for_parameters_that_differ_only_by_suffix = true,
--           dotnet_suppress_inlay_hints_for_parameters_that_match_argument_name = true,
--           dotnet_suppress_inlay_hints_for_parameters_that_match_method_intent = true,
--         },
--         ["csharp|code_lens"] = {
--           dotnet_enable_references_code_lens = false,
--           dotnet_enable_tests_code_lens = false,
--         },
--         ["csharp|completion"] = {
--           dotnet_provide_regex_completions = true,
--           dotnet_show_completion_items_from_unimported_namespaces = true,
--           dotnet_show_name_completion_suggestions = true,
--         },
--         ["csharp|background_analysis"] = {
--           dotnet_analyzer_diagnostics_scope = "openFiles",
--           dotnet_compiler_diagnostics_scope = "openFiles",
--         },
--       },
--     })
--   end,
-- }
